### ISSUE TITLE
function map definition

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/rml-core#11]
@andimou 's comment (putting it here so the discussion doesn't get lost):

>I think when we defined this back in the days we had in mind a superclass of Term Map and Function Map as it might be a bit incorrect to say that the Function Map is a type of Term Map, because a Term Map expects at least one of the reference/template/constant or none but a term type to specify it's a blank node, whereas the Function Map as you also mention, expects a triples map.

> In principle it's something like, an RDF term is generated by
>- a Term Map, which may be
>    - reference-based
>    - constant-based
>    - template-based
>    - none of the above but with term type blank node
>- Function Map
>ie a function map is an alternative to what nowadays is a term map

>(r I don't remember correct?)

**Comment by bjdmeest** [comment]
Yeah. I think those are the two options:

- DEF1 "function map is a type of term map"
- DEF2 "there's a superclass of term map, that can be term map or function map"

I don't know which one is best. Reason I took DEF1 right now, is because then it's easier to align with all different (R2)RML shenanigans about "subjectmap vs predicatemap vs objectmap vs graphmap" (processing depends on those).
Currently, it's stated that `this term map has two classes: fnml:FunctionMap, and the term map within the context of the RML Mapping, namely, subject map, predicate map, object map, or graph map` (so you have to take both into account when processing)

If we say that function map is DEF2, then I have the feeling we also need to define things such as "a functionSubjectMap/functionPredicateMap/...", for example, to clarify similar processing as in https://rml.io/specs/rml/#termtype (it's the termtype thing again 😅 ).

WDYT? There might also be other options though

**Comment by bjdmeest** [comment]
BUT, if we would use DEF1, then we need to clarify that a term map may be

- reference-based
- constant-based
- template-based
- none of the above but with term type blank node
- **a function map**

**Comment by andimou** [comment]
I get what you mean, it's also inherited reasoning from RML, but if we want to finally be 100% correct, we do need a superclass that allows us to bring everything correct. Then we would have something like this

* `rml:newSuperTermMap`
  * `rml:TermMap`
  * `rr:TermMap`
  * `fnml:FunctionMap`

where `rml:TermMap`, `rr:TermMap` and `fnml:FunctionMap` are subclasses of the newSuperTermMap

and that would also make everything more correct because the Term Map is actually abused in the case of RML, as an `rr:TermMap` should have one of column/template/reference and not reference that the `rml:TermMap` should have.

RML was on purposed designed to abuse R2RML vocab, but as it is now, the cleanest solution would be to revise the RML vocabulary to correctly generalize R2RML.

If we make things valid, ie as explained above, then I think the best would be to straight go for a correct definition of `fnml:FunctionMap`


(it might even be like the following, ie the `rr:TermMap` a subclass of `rml:TermMap` but that might not matter for the discussion here
* `rml:newSuperTermMap`
  * `rml:TermMap`
    * `rr:TermMap`
  * `fnml:FunctionMap`)

**Comment by bjdmeest** [comment]
For my understanding and completeness: what would be the range of, e.g. `rml:subjectMap`? Following R2RML, I assume it would be `rml:SubjectMap`? And if that subject map would actually specify that it's a `fnml:FunctionMap`, then the class of that subject map would be both `rml:SubjectMap AND fnml:FunctionMap`? I would be fine with that, and I guess that means we don't need specific `fnml:FunctionSubjectMap` (which I think is an advantage).

I'd propose to add a reference to this issue in the current draft near the definition of function map, and leave this issue open, as we probably first want to discuss this in the RML spec before getting into too much details here :)

**Comment by bjdmeest** [comment]
(if you prefer, I could also change to "a function map is an alternative to what nowadays is a term map" for now)

**Comment by pmaria** [comment]
As a `fnml:FunctionMap` is also a "A function that generates an RDF term", it should be a sub class of `rml:TermMap` IMO. So I would think a hierarchy of 
* `rml:TermMap`
  * `rr:TermMap` - every R2RML term map is also an RML term map
  * `fnml:FunctionMap` - every FNML function map is also an RML term map

would be sufficient. 

So e.g. stating
```
<#some-triples-map>
  rr:subjectMap <#some-subject-map> .
.

<#some-subjectMap> 
  fnml:functionValue <#some-function-triples-map> 
.
```

would entail

```
<#some-triples-map>
  rr:subjectMap <#some-subject-map> ;
  rml:subjectMap <#some-subject-map> ;
.

<#some-subject-map> a fnml:FunctionMap, rr:TermMap, rml:TermMap ;
  fnml:functionValue <#some-function-triples-map> 
.
```

**Comment by bjdmeest** [comment]
I also have the feeling one level of abstraction would be enough, but for completeness, I think the entailment would be as follow :)

```turtle
<#some-subject-map> a fnml:FunctionMap, rr:TermMap, rml:TermMap, rr:SubjectMap, rml:SubjectMap .
```

**Comment by samiscoding** [comment]
I understand the original definition of the `fnml:FunctionMap` better now with your explanations. I think what @andimou suggests regarding defining a superClass is more precise. Yet, the more I think about the features and application of `fnml:FunctionMap` the more I find it similar to `rr:triplesMap` e.g. `fnml:FunctionMap` can be referred to from another `rr:triplesMap` as its `rr:subjectMap` or `rr:objectMap` or `rr:predicateMap`. We can even refer to it via `rr:joinCondition` since `fnml:FunctionMap` allows to define the `rml:logicalSource` (right?) 
How I visualize it is more like:
```
rml:newSuperTriplesMap
    rr:TermMap
    fnml:FunctionMap
```
What do you think?

**Comment by bjdmeest** [comment]
@samiscoding actually a function map _refers to_ a triples map via the predicate `fnml:functionValue`, see the picture under https://kg-construct.github.io/rml-fno-spec/#fnml . And it's that triples map that allows to define a logical source.
As a function map can be referred from `rr:subjectMap/...`, it's more close to a term map than to a triples map.

I'm not sure about your visualization, does it denote 'parent-child' relations, i.e. a newSuperTriplesMap can refer to term maps or function maps ?
I understood @pmaria 's visulalization as denoting 'subclass' relations, i.e. an rr:TermMap is a subclass of rml:TermMap

**Comment by bjdmeest** [comment]
Given this confusion, I think it makes sense to rename `fnml:FunctionMap` to `fnml:FunctionTermMap`, and maybe at the same time introduce a `fnml:FunctionTriplesMap`, which is de range of `fnml:functionValue`, and a subclass of `r:TriplesMap`, where logicalSource and subjectMap are optional

**Comment by pmaria** [comment]
+1 @bjdmeest , I think that would be clearer.

**Comment by samiscoding** [comment]
> Given this confusion, I think it makes sense to rename `fnml:FunctionMap` to `fnml:FunctionTermMap`, and maybe at the same time introduce a `fnml:FunctionTriplesMap`, which is de range of `fnml:functionValue`, and a subclass of `r:TriplesMap`, where logicalSource and subjectMap are optional

I think that would be the best @bjdmeest since in this way we can also define the join in/between the sources easily and precisely.

**Comment by dachafra** [comment]
> Given this confusion, I think it makes sense to rename `fnml:FunctionMap` to `fnml:FunctionTermMap`, and maybe at the same time introduce a `fnml:FunctionTriplesMap`, which is de range of `fnml:functionValue`, and a subclass of `r:TriplesMap`, where logicalSource and subjectMap are optional

+1

**Comment by pmaria** [comment]
@samiscoding what issue do you mean exactly? Can you give an example?

**Comment by samiscoding** [comment]
What I refer to are all the cases around referencing in one source or between sources when `fnml:functionMap `involving #1 and #2 , test case `RMLFNOTC0009-CSV` and `RMLFNOTC0019-CSV`. But the specific case I have in mind is when one wants to join two sources via `rr:joinCondition` and the object is the outcome of the `fnml:functionMap` over the second source. e.g.

Source1:
A | B
-- | --
a1 | b1
a2 | b2

Source2:
C | B
-- | --
c1 | b1
c2 | b2
 
The mapping should be sth like this: (but it is currently **incorrect** since` fnml:functionMap `is not a `rr:triplesMap` )

<#TriplesMap1>
  a rr:TriplesMap;
  rml:logicalSource [
    rml:source "source1.csv";
    rml:referenceFormulation ql:CSV ];

  rr:subjectMap [
    rr:template "A" ]; 

  rr:predicateObjectMap [
    rr:predicate ex:sth;
    rr:objectMap [
      rr:parentTriplesMap <#FunctionMap1>;
      rr:joinCondition [
        rr:child "B";
        rr:parent "B";
      ]; ];].

<#FunctionMap1>
    fnml:functionValue [
        rml:logicalSource [ rml:source "source2.csv";
        rml:referenceFormulation ql:CSV ];

        rr:predicateObjectMap [
            rr:predicate fno:executes ;
            rr:objectMap [ 
                rr:constant ex:functionName 
            ] ];
        rr:predicateObjectMap [
            rr:predicate ex:value1;
            rr:objectMap [ 
                 rml:reference "C"
            ]
        ]; ].

**Comment by dachafra** [comment]
the definition from the property `rr:parentTriplesMap` in R2RML says: _The objects will be generated from the subject map of the parent triples map_ 
I liked the idea of having this kind of rules with functions, indeed it was what I was trying to represent in #1 but an extension or new property may be needed

**Comment by andimou** [comment]
shall we perhaps keep the discussion related to #1 under #1 so we don't mix many aspects in this issue?

**Comment by andimou** [comment]
How do you consider `fnml:FunctionTriplesMap` different compared to `rml:TriplesMap`? 

(I mention `rml:TriplesMap` bc eventually we will need to bring them all to the `rml` namespace to properly define the ontology terms)

**Comment by bjdmeest** [comment]
> How do you consider `fnml:FunctionTriplesMap` different compared to `rml:TriplesMap`?

@andimou compared to `rr:TripleMap`, `fnml:FunctionTriplesMap` has optional logicalSource and subjectMap. Of course if `rml:TriplesMap` would also consider logicalSource and subjectMap optional, then the distinction is - I think - no longer needed, but that depends on the definition of `rml:TriplesMap` :)

**Comment by pmaria** [comment]
I can see an optional subjectMap property as also being applicable to `rml:TriplesMap`. 
This would then generate a blank node with a random id for each iteration.

**Comment by pmaria** [comment]
> I can see an optional subjectMap property as also being applicable to rml:TriplesMap.
This would then generate a blank node with a random id for each iteration.

Hmm on second thought, this might not be so easy for engines to comply with, irt joins on such a triples map. So we should proceed with caution.

**Comment by bjdmeest** [comment]
> Hmm on second thought, this might not be so easy for engines to comply with, wrt joins on such a triples map. So we should proceed with caution.

Well, just as hard as when [joining on a triples map with subjectmap's termtype rr:BlankNode](https://www.w3.org/2001/sw/rdb2rdf/test-cases/#R2RMLTC0014c), no? I think this is more like a shortcut, not really change or extension of behavior

**Comment by pmaria** [comment]
In the R2RML test you point to the blank node id is determined by value of `rr:column` , so the blank node id can be determined deterministically and repeatably. 

But when you don't have this, all you can do is generate a random blank node. However, this limits the way you can implement joins, because you need to use the same blanknode id in a different TriplesMap execution. 

Not saying that is a bad thing per se. But it can have significant impact on implementations.

**Comment by bjdmeest** [comment]
Huh, I guess I never fully realized that in R2RML it is implied that every node's URI (even when it's a blank) is deterministically defined when it's not a direct mapping. Given we can use a random-generator as a function to generate a URI for a subjectmap, that implication is gone. So I have the feeling we either need to specify that only deterministic functions can be used for subject maps, or we need to handle this problem in any case, independent of whether we make subject map optional or not.

**Comment by pmaria** [comment]
Yes, I think we should raise the generation of random subject names as its own issue on the RML side.

**Comment by andimou** [comment]
(moved the discussion about the RML term maps to another issue so we can conclude here the discussions on FnO)

**Comment by dachafra** [comment]
If it makes sense, this can be transferred to https://github.com/kg-construct/fnml-spec

**Comment by bjdmeest** [comment]
I think this should be revisited based on https://kg-construct.github.io/fnml-spec/ , I vote to close bc it's deprecated
