### ISSUE TITLE
(Data) Errors

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#32]
The Data Errors subsection of [R2]RML core specification might need some updating, perhaps also considering revised test cases.

**Comment by dachafra** [comment]
IMO the spec in R2RML is ok in this section. Apart from minor "syntactic-sugar" changes (database by source, etc) I don't think that we need to change the rest.

**Comment by DylanVanAssche** [comment]
Shouldn't we also define errors here? I noticed that things are all different here regarding Data Errors in engines.
Some exit, some do their 'best' to map the rest, etc. even though they should give an error.
However, the latter is not very clear in the R2RML spec, could we maybe define how the error should be reported?

Example: 'Should return error' --> Error X is returned because of Y

**Comment by dachafra** [comment]
the spec says

```
A conforming [R2RML processor](https://www.w3.org/TR/r2rml/#dfn-r2rml-processor) may, however, allow other operations that do not require inspecting or returning these [RDF terms](https://www.w3.org/TR/r2rml/#dfn-rdf-term), and thus may provide partial access to an [output dataset](https://www.w3.org/TR/r2rml/#dfn-output-dataset) that contains data errors. Nevertheless, an [R2RML processor](https://www.w3.org/TR/r2rml/#dfn-r2rml-processor) should report data errors as early as possible.
```

So... @DylanVanAssche are you proposing to be a bit more explicit with the behavior of the enignes?

**Comment by DylanVanAssche** [comment]
@dachafra Yes, a little bit more explicit about this:

> should report data errors

Reporting errors is really vague.
Would be great if we could have a set of known errors with IDs & IRIs like:

- Invalid mapping rules
  - Incomplete Logical Source
  - Missing Triples Map/Subject Map/ ...
  - Invalid reference (broken XPath for example)
  - ...
- Data error
  - Invalid blablabla
- Unknown error (when it doesn't fit anywhere in the defined ones)

This way, you can properly test in the test cases if a test case expects an error you return the right error.
Example: failure because of a data error, not because you made accidentally a typo in the test case mapping rules.

How exactly the engine reports this, doesn't really matter I think since that depends on the implementation, programming language, etc. Some may use exit codes, others return RDF describing the error code, etc.

**Comment by DylanVanAssche** [comment]
I made a list of them a while ago, maybe not 100% complete, but close: https://docs.google.com/spreadsheets/d/1he_dk9IxCLsSCzSzPjBlXfTIKVycpEDhgjbnFDh8JJU/edit?usp=sharing

**Comment by dachafra** [comment]
> @dachafra Yes, a little bit more explicit about this:
> 
> > should report data errors
> 
> Reporting errors is really vague. Would be great if we could have a set of known errors with IDs & IRIs like:
> 
> * Invalid mapping rules
>   
>   * Incomplete Logical Source
>   * Missing Triples Map/Subject Map/ ...
>   * Invalid reference (broken XPath for example)
>   * ...

Well, invalid mappings will be reported by SHACL shapes right? Do engines need to still validate the mapping rules?

> * Data error
>   
>   * Invalid blablabla
> * Unknown error (when it doesn't fit anywhere in the defined ones)

Agree, but this is more a "good-to-have", move to best practices repo? (not sure)

> This way, you can properly test in the test cases if a test case expects an error you return the right error. Example: failure because of a data error, not because you made accidentally a typo in the test case mapping rules.
> 
> How exactly the engine reports this, doesn't really matter I think since that depends on the implementation, programming language, etc. Some may use exit codes, others return RDF describing the error code, etc.

**Comment by DylanVanAssche** [comment]
> Well, invalid mappings will be reported by SHACL shapes right? Do engines need to still validate the mapping rules?

Yes, that's the idea for mappings.

> Agree, but this is more a "good-to-have", move to best practices repo? (not sure)

Fine for me, but this would make the behavior of engines more predictable.
It is not a hard requirement though, just a suggestion :)

**Comment by dachafra** [comment]
> I made a list of them a while ago, maybe not 100% complete, but close: https://docs.google.com/spreadsheets/d/1he_dk9IxCLsSCzSzPjBlXfTIKVycpEDhgjbnFDh8JJU/edit?usp=sharing

this is super valuable!! Can I added to the agenda?

**Comment by DylanVanAssche** [comment]
@dachafra Euhm sure, FYI this is only a list I made from experience when dealing with engines and their code. Nothing scientific :sweat_smile:

**Comment by DylanVanAssche** [comment]
Fine for me!
